// Friendly timezone name mapping — IANA timezone to "Country (City)"
// Covers all standard IANA timezones and aliases with uniform "Country (City)" formatting.
// Falls back to a formatted region/city name if an unlisted timezone is encountered.
// Storage and validation always use the standard IANA identifiers.

export const TIMEZONE_FRIENDLY_NAMES = {
  // Asia
  'Asia/Aden': 'Yemen (Aden)',
  'Asia/Almaty': 'Kazakhstan (Almaty)',
  'Asia/Amman': 'Jordan (Amman)',
  'Asia/Anadyr': 'Russia (Anadyr)',
  'Asia/Aqtau': 'Kazakhstan (Aqtau)',
  'Asia/Aqtobe': 'Kazakhstan (Aqtobe)',
  'Asia/Ashgabat': 'Turkmenistan (Ashgabat)',
  'Asia/Atyrau': 'Kazakhstan (Atyrau)',
  'Asia/Baghdad': 'Iraq (Baghdad)',
  'Asia/Bahrain': 'Bahrain (Manama)',
  'Asia/Baku': 'Azerbaijan (Baku)',
  'Asia/Bangkok': 'Thailand (Bangkok)',
  'Asia/Barnaul': 'Russia (Barnaul)',
  'Asia/Beijing': 'China (Beijing)',
  'Asia/Beirut': 'Lebanon (Beirut)',
  'Asia/Bishkek': 'Kyrgyzstan (Bishkek)',
  'Asia/Brunei': 'Brunei (Bandar Seri Begawan)',
  'Asia/Calcutta': 'India (Kolkata)',
  'Asia/Kolkata': 'India (Kolkata)',
  'Asia/Mumbai': 'India (Mumbai)',
  'Asia/Delhi': 'India (Delhi)',
  'Asia/Chennai': 'India (Chennai)',
  'Asia/Bangalore': 'India (Bangalore)',
  'Asia/Chita': 'Russia (Chita)',
  'Asia/Choibalsan': 'Mongolia (Choibalsan)',
  'Asia/Colombo': 'Sri Lanka (Colombo)',
  'Asia/Damascus': 'Syria (Damascus)',
  'Asia/Dhaka': 'Bangladesh (Dhaka)',
  'Asia/Dili': 'East Timor (Dili)',
  'Asia/Dubai': 'UAE (Dubai)',
  'Asia/Dushanbe': 'Tajikistan (Dushanbe)',
  'Asia/Famagusta': 'Cyprus (Famagusta)',
  'Asia/Gaza': 'Palestine (Gaza)',
  'Asia/Hebron': 'Palestine (Hebron)',
  'Asia/Hong_Kong': 'Hong Kong (Hong Kong)',
  'Asia/Hovd': 'Mongolia (Hovd)',
  'Asia/Irkutsk': 'Russia (Irkutsk)',
  'Asia/Jakarta': 'Indonesia (Jakarta)',
  'Asia/Jayapura': 'Indonesia (Jayapura)',
  'Asia/Jerusalem': 'Israel (Jerusalem)',
  'Asia/Kabul': 'Afghanistan (Kabul)',
  'Asia/Kamchatka': 'Russia (Petropavlovsk-Kamchatsky)',
  'Asia/Karachi': 'Pakistan (Karachi)',
  'Asia/Katmandu': 'Nepal (Kathmandu)',
  'Asia/Kathmandu': 'Nepal (Kathmandu)',
  'Asia/Khandyga': 'Russia (Khandyga)',
  'Asia/Krasnoyarsk': 'Russia (Krasnoyarsk)',
  'Asia/Kuala_Lumpur': 'Malaysia (Kuala Lumpur)',
  'Asia/Kuching': 'Malaysia (Kuching)',
  'Asia/Kuwait': 'Kuwait (Kuwait City)',
  'Asia/Macau': 'Macau (Macau)',
  'Asia/Magadan': 'Russia (Magadan)',
  'Asia/Makassar': 'Indonesia (Makassar)',
  'Asia/Manila': 'Philippines (Manila)',
  'Asia/Muscat': 'Oman (Muscat)',
  'Asia/Nicosia': 'Cyprus (Nicosia)',
  'Asia/Novokuznetsk': 'Russia (Novokuznetsk)',
  'Asia/Novosibirsk': 'Russia (Novosibirsk)',
  'Asia/Omsk': 'Russia (Omsk)',
  'Asia/Oral': 'Kazakhstan (Oral)',
  'Asia/Phnom_Penh': 'Cambodia (Phnom Penh)',
  'Asia/Pontianak': 'Indonesia (Pontianak)',
  'Asia/Pyongyang': 'North Korea (Pyongyang)',
  'Asia/Qatar': 'Qatar (Doha)',
  'Asia/Qostanay': 'Kazakhstan (Kostanay)',
  'Asia/Qyzylorda': 'Kazakhstan (Kyzylorda)',
  'Asia/Rangoon': 'Myanmar (Yangon)',
  'Asia/Yangon': 'Myanmar (Yangon)',
  'Asia/Riyadh': 'Saudi Arabia (Riyadh)',
  'Asia/Saigon': 'Vietnam (Ho Chi Minh City)',
  'Asia/Ho_Chi_Minh': 'Vietnam (Ho Chi Minh City)',
  'Asia/Sakhalin': 'Russia (Yuzhno-Sakhalinsk)',
  'Asia/Samarkand': 'Uzbekistan (Samarkand)',
  'Asia/Seoul': 'South Korea (Seoul)',
  'Asia/Shanghai': 'China (Shanghai)',
  'Asia/Singapore': 'Singapore (Singapore)',
  'Asia/Srednekolymsk': 'Russia (Srednekolymsk)',
  'Asia/Taipei': 'Taiwan (Taipei)',
  'Asia/Tashkent': 'Uzbekistan (Tashkent)',
  'Asia/Tbilisi': 'Georgia (Tbilisi)',
  'Asia/Tehran': 'Iran (Tehran)',
  'Asia/Thimphu': 'Bhutan (Thimphu)',
  'Asia/Tokyo': 'Japan (Tokyo)',
  'Asia/Tomsk': 'Russia (Tomsk)',
  'Asia/Ulaanbaatar': 'Mongolia (Ulaanbaatar)',
  'Asia/Urumqi': 'China (Urumqi)',
  'Asia/Ust-Nera': 'Russia (Ust-Nera)',
  'Asia/Vientiane': 'Laos (Vientiane)',
  'Asia/Vladivostok': 'Russia (Vladivostok)',
  'Asia/Yakutsk': 'Russia (Yakutsk)',
  'Asia/Yekaterinburg': 'Russia (Yekaterinburg)',
  'Asia/Yerevan': 'Armenia (Yerevan)',

  // Europe
  'Europe/Amsterdam': 'Netherlands (Amsterdam)',
  'Europe/Andorra': 'Andorra (Andorra la Vella)',
  'Europe/Astrakhan': 'Russia (Astrakhan)',
  'Europe/Athens': 'Greece (Athens)',
  'Europe/Belgrade': 'Serbia (Belgrade)',
  'Europe/Berlin': 'Germany (Berlin)',
  'Europe/Bratislava': 'Slovakia (Bratislava)',
  'Europe/Brussels': 'Belgium (Brussels)',
  'Europe/Bucharest': 'Romania (Bucharest)',
  'Europe/Budapest': 'Hungary (Budapest)',
  'Europe/Busingen': 'Germany (Busingen)',
  'Europe/Chisinau': 'Moldova (Chisinau)',
  'Europe/Copenhagen': 'Denmark (Copenhagen)',
  'Europe/Dublin': 'Ireland (Dublin)',
  'Europe/Gibraltar': 'Gibraltar (Gibraltar)',
  'Europe/Guernsey': 'UK (Guernsey)',
  'Europe/Helsinki': 'Finland (Helsinki)',
  'Europe/Isle_of_Man': 'UK (Isle of Man)',
  'Europe/Istanbul': 'Turkey (Istanbul)',
  'Europe/Jersey': 'UK (Jersey)',
  'Europe/Kaliningrad': 'Russia (Kaliningrad)',
  'Europe/Kiev': 'Ukraine (Kyiv)',
  'Europe/Kyiv': 'Ukraine (Kyiv)',
  'Europe/Kirov': 'Russia (Kirov)',
  'Europe/Lisbon': 'Portugal (Lisbon)',
  'Europe/Ljubljana': 'Slovenia (Ljubljana)',
  'Europe/London': 'UK (London)',
  'Europe/Luxembourg': 'Luxembourg (Luxembourg)',
  'Europe/Madrid': 'Spain (Madrid)',
  'Europe/Malta': 'Malta (Valletta)',
  'Europe/Mariehamn': 'Finland (Mariehamn)',
  'Europe/Minsk': 'Belarus (Minsk)',
  'Europe/Monaco': 'Monaco (Monaco)',
  'Europe/Moscow': 'Russia (Moscow)',
  'Europe/Oslo': 'Norway (Oslo)',
  'Europe/Paris': 'France (Paris)',
  'Europe/Podgorica': 'Montenegro (Podgorica)',
  'Europe/Prague': 'Czech Republic (Prague)',
  'Europe/Riga': 'Latvia (Riga)',
  'Europe/Rome': 'Italy (Rome)',
  'Europe/Samara': 'Russia (Samara)',
  'Europe/San_Marino': 'San Marino (San Marino)',
  'Europe/Sarajevo': 'Bosnia & Herzegovina (Sarajevo)',
  'Europe/Saratov': 'Russia (Saratov)',
  'Europe/Simferopol': 'Russia (Simferopol)',
  'Europe/Skopje': 'North Macedonia (Skopje)',
  'Europe/Sofia': 'Bulgaria (Sofia)',
  'Europe/Stockholm': 'Sweden (Stockholm)',
  'Europe/Tallinn': 'Estonia (Tallinn)',
  'Europe/Tirane': 'Albania (Tirana)',
  'Europe/Ulyanovsk': 'Russia (Ulyanovsk)',
  'Europe/Uzhgorod': 'Ukraine (Uzhhorod)',
  'Europe/Vaduz': 'Liechtenstein (Vaduz)',
  'Europe/Vatican': 'Vatican City (Vatican City)',
  'Europe/Vienna': 'Austria (Vienna)',
  'Europe/Vilnius': 'Lithuania (Vilnius)',
  'Europe/Volgograd': 'Russia (Volgograd)',
  'Europe/Warsaw': 'Poland (Warsaw)',
  'Europe/Zagreb': 'Croatia (Zagreb)',
  'Europe/Zaporozhye': 'Ukraine (Zaporizhzhia)',
  'Europe/Zurich': 'Switzerland (Zurich)',

  // Africa
  'Africa/Abidjan': 'Ivory Coast (Abidjan)',
  'Africa/Accra': 'Ghana (Accra)',
  'Africa/Addis_Ababa': 'Ethiopia (Addis Ababa)',
  'Africa/Algiers': 'Algeria (Algiers)',
  'Africa/Asmara': 'Eritrea (Asmara)',
  'Africa/Asmera': 'Eritrea (Asmara)',
  'Africa/Bamako': 'Mali (Bamako)',
  'Africa/Bangui': 'Central African Republic (Bangui)',
  'Africa/Banjul': 'Gambia (Banjul)',
  'Africa/Bissau': 'Guinea-Bissau (Bissau)',
  'Africa/Blantyre': 'Malawi (Blantyre)',
  'Africa/Brazzaville': 'Congo (Brazzaville)',
  'Africa/Bujumbura': 'Burundi (Bujumbura)',
  'Africa/Cairo': 'Egypt (Cairo)',
  'Africa/Casablanca': 'Morocco (Casablanca)',
  'Africa/Ceuta': 'Spain (Ceuta)',
  'Africa/Conakry': 'Guinea (Conakry)',
  'Africa/Dakar': 'Senegal (Dakar)',
  'Africa/Dar_es_Salaam': 'Tanzania (Dar es Salaam)',
  'Africa/Djibouti': 'Djibouti (Djibouti)',
  'Africa/Douala': 'Cameroon (Douala)',
  'Africa/El_Aaiun': 'Western Sahara (El Aaiun)',
  'Africa/Freetown': 'Sierra Leone (Freetown)',
  'Africa/Gaborone': 'Botswana (Gaborone)',
  'Africa/Harare': 'Zimbabwe (Harare)',
  'Africa/Johannesburg': 'South Africa (Johannesburg)',
  'Africa/Juba': 'South Sudan (Juba)',
  'Africa/Kampala': 'Uganda (Kampala)',
  'Africa/Khartoum': 'Sudan (Khartoum)',
  'Africa/Kigali': 'Rwanda (Kigali)',
  'Africa/Kinshasa': 'DR Congo (Kinshasa)',
  'Africa/Lagos': 'Nigeria (Lagos)',
  'Africa/Libreville': 'Gabon (Libreville)',
  'Africa/Lilongwe': 'Malawi (Lilongwe)',
  'Africa/Lome': 'Togo (Lome)',
  'Africa/Luanda': 'Angola (Luanda)',
  'Africa/Lubumbashi': 'DR Congo (Lubumbashi)',
  'Africa/Lusaka': 'Zambia (Lusaka)',
  'Africa/Malabo': 'Equatorial Guinea (Malabo)',
  'Africa/Maputo': 'Mozambique (Maputo)',
  'Africa/Maseru': 'Lesotho (Maseru)',
  'Africa/Mbabane': 'Eswatini (Mbabane)',
  'Africa/Mogadishu': 'Somalia (Mogadishu)',
  'Africa/Monrovia': 'Liberia (Monrovia)',
  'Africa/Nairobi': 'Kenya (Nairobi)',
  'Africa/Ndjamena': 'Chad (N\'Djamena)',
  'Africa/Niamey': 'Niger (Niamey)',
  'Africa/Nouakchott': 'Mauritania (Nouakchott)',
  'Africa/Ouagadougou': 'Burkina Faso (Ouagadougou)',
  'Africa/Porto-Novo': 'Benin (Porto-Novo)',
  'Africa/Sao_Tome': 'Sao Tome & Principe (Sao Tome)',
  'Africa/Tripoli': 'Libya (Tripoli)',
  'Africa/Tunis': 'Tunisia (Tunis)',
  'Africa/Windhoek': 'Namibia (Windhoek)',
  'Africa/Yaounde': 'Cameroon (Yaounde)',

  // North America
  'America/Adak': 'USA (Adak)',
  'America/Anchorage': 'USA (Anchorage)',
  'America/Anguilla': 'Anguilla (The Valley)',
  'America/Antigua': 'Antigua & Barbuda (St. John\'s)',
  'America/Aruba': 'Aruba (Oranjestad)',
  'America/Bahia_Banderas': 'Mexico (Bahia de Banderas)',
  'America/Barbados': 'Barbados (Bridgetown)',
  'America/Belize': 'Belize (Belmopan)',
  'America/Blanc-Sablon': 'Canada (Blanc-Sablon)',
  'America/Boise': 'USA (Boise)',
  'America/Cambridge_Bay': 'Canada (Cambridge Bay)',
  'America/Cancun': 'Mexico (Cancun)',
  'America/Cayman': 'Cayman Islands (George Town)',
  'America/Chicago': 'USA (Chicago)',
  'America/Chihuahua': 'Mexico (Chihuahua)',
  'America/Ciudad_Juarez': 'Mexico (Ciudad Juarez)',
  'America/Coral_Harbour': 'Canada (Coral Harbour)',
  'America/Costa_Rica': 'Costa Rica (San Jose)',
  'America/Creston': 'Canada (Creston)',
  'America/Curacao': 'Curacao (Willemstad)',
  'America/Danmarkshavn': 'Greenland (Danmarkshavn)',
  'America/Dawson': 'Canada (Dawson)',
  'America/Dawson_Creek': 'Canada (Dawson Creek)',
  'America/Denver': 'USA (Denver)',
  'America/Detroit': 'USA (Detroit)',
  'America/Dominica': 'Dominica (Roseau)',
  'America/Edmonton': 'Canada (Edmonton)',
  'America/El_Salvador': 'El Salvador (San Salvador)',
  'America/Fort_Nelson': 'Canada (Fort Nelson)',
  'America/Fortaleza': 'Brazil (Fortaleza)',
  'America/Glace_Bay': 'Canada (Glace Bay)',
  'America/Godthab': 'Greenland (Nuuk)',
  'America/Goose_Bay': 'Canada (Goose Bay)',
  'America/Grand_Turk': 'Turks & Caicos (Grand Turk)',
  'America/Grenada': 'Grenada (St. George\'s)',
  'America/Guadeloupe': 'Guadeloupe (Basse-Terre)',
  'America/Guatemala': 'Guatemala (Guatemala City)',
  'America/Halifax': 'Canada (Halifax)',
  'America/Havana': 'Cuba (Havana)',
  'America/Hermosillo': 'Mexico (Hermosillo)',
  'America/Indiana/Indianapolis': 'USA (Indianapolis)',
  'America/Indiana/Knox': 'USA (Indiana - Knox)',
  'America/Indiana/Marengo': 'USA (Indiana - Marengo)',
  'America/Indiana/Petersburg': 'USA (Indiana - Petersburg)',
  'America/Indiana/Tell_City': 'USA (Indiana - Tell City)',
  'America/Indiana/Vevay': 'USA (Indiana - Vevay)',
  'America/Indiana/Vincennes': 'USA (Indiana - Vincennes)',
  'America/Indiana/Winamac': 'USA (Indiana - Winamac)',
  'America/Indianapolis': 'USA (Indianapolis)',
  'America/Inuvik': 'Canada (Inuvik)',
  'America/Iqaluit': 'Canada (Iqaluit)',
  'America/Jamaica': 'Jamaica (Kingston)',
  'America/Juneau': 'USA (Juneau)',
  'America/Kentucky/Louisville': 'USA (Louisville)',
  'America/Kentucky/Monticello': 'USA (Kentucky - Monticello)',
  'America/Kralendijk': 'Bonaire (Kralendijk)',
  'America/Los_Angeles': 'USA (Los Angeles)',
  'America/Louisville': 'USA (Louisville)',
  'America/Lower_Princes': 'Sint Maarten (Lower Prince\'s Quarter)',
  'America/Managua': 'Nicaragua (Managua)',
  'America/Marigot': 'Saint Martin (Marigot)',
  'America/Martinique': 'Martinique (Fort-de-France)',
  'America/Matamoros': 'Mexico (Matamoros)',
  'America/Mazatlan': 'Mexico (Mazatlan)',
  'America/Menominee': 'USA (Menominee)',
  'America/Merida': 'Mexico (Merida)',
  'America/Metlakatla': 'USA (Metlakatla)',
  'America/Mexico_City': 'Mexico (Mexico City)',
  'America/Miquelon': 'St. Pierre & Miquelon (Miquelon)',
  'America/Moncton': 'Canada (Moncton)',
  'America/Monterrey': 'Mexico (Monterrey)',
  'America/Montreal': 'Canada (Montreal)',
  'America/Montserrat': 'Montserrat (Plymouth)',
  'America/Nassau': 'Bahamas (Nassau)',
  'America/New_York': 'USA (New York)',
  'America/Nome': 'USA (Nome)',
  'America/North_Dakota/Beulah': 'USA (North Dakota - Beulah)',
  'America/North_Dakota/Center': 'USA (North Dakota - Center)',
  'America/North_Dakota/New_Salem': 'USA (North Dakota - New Salem)',
  'America/Nuuk': 'Greenland (Nuuk)',
  'America/Ojinaga': 'Mexico (Ojinaga)',
  'America/Panama': 'Panama (Panama City)',
  'America/Phoenix': 'USA (Phoenix)',
  'America/Port-au-Prince': 'Haiti (Port-au-Prince)',
  'America/Port_of_Spain': 'Trinidad & Tobago (Port of Spain)',
  'America/Puerto_Rico': 'Puerto Rico (San Juan)',
  'America/Rankin_Inlet': 'Canada (Rankin Inlet)',
  'America/Regina': 'Canada (Regina)',
  'America/Resolute': 'Canada (Resolute)',
  'America/Santo_Domingo': 'Dominican Republic (Santo Domingo)',
  'America/Scoresbysund': 'Greenland (Ittoqqortoormiit)',
  'America/Sitka': 'USA (Sitka)',
  'America/St_Barthelemy': 'St. Barthelemy (Gustavia)',
  'America/St_Johns': 'Canada (St. John\'s)',
  'America/St_Kitts': 'St. Kitts & Nevis (Basseterre)',
  'America/St_Lucia': 'St. Lucia (Castries)',
  'America/St_Thomas': 'US Virgin Islands (Charlotte Amalie)',
  'America/St_Vincent': 'St. Vincent & Grenadines (Kingstown)',
  'America/Swift_Current': 'Canada (Swift Current)',
  'America/Tegucigalpa': 'Honduras (Tegucigalpa)',
  'America/Thule': 'Greenland (Thule)',
  'America/Tijuana': 'Mexico (Tijuana)',
  'America/Toronto': 'Canada (Toronto)',
  'America/Tortola': 'British Virgin Islands (Road Town)',
  'America/Trinidad': 'Trinidad & Tobago (Port of Spain)',
  'America/Turks_Caicos': 'Turks & Caicos (Grand Turk)',
  'America/Vancouver': 'Canada (Vancouver)',
  'America/Whitehorse': 'Canada (Whitehorse)',
  'America/Winnipeg': 'Canada (Winnipeg)',
  'America/Yakutat': 'USA (Yakutat)',
  'America/Yellowknife': 'Canada (Yellowknife)',

  // South America
  'America/Araguaina': 'Brazil (Araguaina)',
  'America/Argentina/Buenos_Aires': 'Argentina (Buenos Aires)',
  'America/Argentina/Catamarca': 'Argentina (Catamarca)',
  'America/Argentina/Cordoba': 'Argentina (Cordoba)',
  'America/Argentina/Jujuy': 'Argentina (Jujuy)',
  'America/Argentina/La_Rioja': 'Argentina (La Rioja)',
  'America/Argentina/Mendoza': 'Argentina (Mendoza)',
  'America/Argentina/Rio_Gallegos': 'Argentina (Rio Gallegos)',
  'America/Argentina/Salta': 'Argentina (Salta)',
  'America/Argentina/San_Juan': 'Argentina (San Juan)',
  'America/Argentina/San_Luis': 'Argentina (San Luis)',
  'America/Argentina/Tucuman': 'Argentina (Tucuman)',
  'America/Argentina/Ushuaia': 'Argentina (Ushuaia)',
  'America/Asuncion': 'Paraguay (Asuncion)',
  'America/Bahia': 'Brazil (Salvador)',
  'America/Belem': 'Brazil (Belem)',
  'America/Boa_Vista': 'Brazil (Boa Vista)',
  'America/Bogota': 'Colombia (Bogota)',
  'America/Buenos_Aires': 'Argentina (Buenos Aires)',
  'America/Campo_Grande': 'Brazil (Campo Grande)',
  'America/Caracas': 'Venezuela (Caracas)',
  'America/Catamarca': 'Argentina (Catamarca)',
  'America/Cayenne': 'French Guiana (Cayenne)',
  'America/Cordoba': 'Argentina (Cordoba)',
  'America/Coyhaique': 'Chile (Coyhaique)',
  'America/Cuiaba': 'Brazil (Cuiaba)',
  'America/Eirunepe': 'Brazil (Eirunepe)',
  'America/Guayaquil': 'Ecuador (Guayaquil)',
  'America/Guyana': 'Guyana (Georgetown)',
  'America/Jujuy': 'Argentina (Jujuy)',
  'America/La_Paz': 'Bolivia (La Paz)',
  'America/La_Rioja': 'Argentina (La Rioja)',
  'America/Lima': 'Peru (Lima)',
  'America/Maceio': 'Brazil (Maceio)',
  'America/Manaus': 'Brazil (Manaus)',
  'America/Mendoza': 'Argentina (Mendoza)',
  'America/Montevideo': 'Uruguay (Montevideo)',
  'America/Noronha': 'Brazil (Fernando de Noronha)',
  'America/Paramaribo': 'Suriname (Paramaribo)',
  'America/Porto_Velho': 'Brazil (Porto Velho)',
  'America/Punta_Arenas': 'Chile (Punta Arenas)',
  'America/Recife': 'Brazil (Recife)',
  'America/Rio_Branco': 'Brazil (Rio Branco)',
  'America/Rio_Gallegos': 'Argentina (Rio Gallegos)',
  'America/Salta': 'Argentina (Salta)',
  'America/San_Juan': 'Argentina (San Juan)',
  'America/San_Luis': 'Argentina (San Luis)',
  'America/Santarem': 'Brazil (Santarem)',
  'America/Santiago': 'Chile (Santiago)',
  'America/Sao_Paulo': 'Brazil (Sao Paulo)',
  'America/Tucuman': 'Argentina (Tucuman)',
  'America/Ushuaia': 'Argentina (Ushuaia)',

  // Australia
  'Australia/Adelaide': 'Australia (Adelaide)',
  'Australia/Brisbane': 'Australia (Brisbane)',
  'Australia/Broken_Hill': 'Australia (Broken Hill)',
  'Australia/Darwin': 'Australia (Darwin)',
  'Australia/Eucla': 'Australia (Eucla)',
  'Australia/Hobart': 'Australia (Hobart)',
  'Australia/Lindeman': 'Australia (Lindeman)',
  'Australia/Lord_Howe': 'Australia (Lord Howe Island)',
  'Australia/Melbourne': 'Australia (Melbourne)',
  'Australia/Perth': 'Australia (Perth)',
  'Australia/Sydney': 'Australia (Sydney)',

  // Antarctica
  'Antarctica/Casey': 'Antarctica (Casey)',
  'Antarctica/Davis': 'Antarctica (Davis)',
  'Antarctica/DumontDUrville': 'Antarctica (Dumont d\'Urville)',
  'Antarctica/Macquarie': 'Antarctica (Macquarie Island)',
  'Antarctica/Mawson': 'Antarctica (Mawson)',
  'Antarctica/McMurdo': 'Antarctica (McMurdo)',
  'Antarctica/Palmer': 'Antarctica (Palmer)',
  'Antarctica/Rothera': 'Antarctica (Rothera)',
  'Antarctica/Syowa': 'Antarctica (Syowa)',
  'Antarctica/Troll': 'Antarctica (Troll)',
  'Antarctica/Vostok': 'Antarctica (Vostok)',

  // Arctic
  'Arctic/Longyearbyen': 'Norway (Longyearbyen)',

  // Atlantic
  'Atlantic/Azores': 'Portugal (Azores)',
  'Atlantic/Bermuda': 'Bermuda (Hamilton)',
  'Atlantic/Canary': 'Spain (Canary Islands)',
  'Atlantic/Cape_Verde': 'Cape Verde (Praia)',
  'Atlantic/Faeroe': 'Faroe Islands (Torshavn)',
  'Atlantic/Madeira': 'Portugal (Madeira)',
  'Atlantic/Reykjavik': 'Iceland (Reykjavik)',
  'Atlantic/South_Georgia': 'South Georgia (Grytviken)',
  'Atlantic/St_Helena': 'St. Helena (Jamestown)',
  'Atlantic/Stanley': 'Falkland Islands (Stanley)',

  // Indian Ocean
  'Indian/Antananarivo': 'Madagascar (Antananarivo)',
  'Indian/Chagos': 'British Indian Ocean Territory (Diego Garcia)',
  'Indian/Christmas': 'Christmas Island (Flying Fish Cove)',
  'Indian/Cocos': 'Cocos Islands (West Island)',
  'Indian/Comoro': 'Comoros (Moroni)',
  'Indian/Kerguelen': 'French Southern Territories (Port-aux-Francais)',
  'Indian/Mahe': 'Seychelles (Mahe)',
  'Indian/Maldives': 'Maldives (Male)',
  'Indian/Mauritius': 'Mauritius (Port Louis)',
  'Indian/Mayotte': 'Mayotte (Mamoudzou)',
  'Indian/Reunion': 'Reunion (Saint-Denis)',

  // Pacific
  'Pacific/Apia': 'Samoa (Apia)',
  'Pacific/Auckland': 'New Zealand (Auckland)',
  'Pacific/Bougainville': 'Papua New Guinea (Bougainville)',
  'Pacific/Chatham': 'New Zealand (Chatham Islands)',
  'Pacific/Easter': 'Chile (Easter Island)',
  'Pacific/Efate': 'Vanuatu (Efate)',
  'Pacific/Enderbury': 'Kiribati (Enderbury)',
  'Pacific/Fakaofo': 'Tokelau (Fakaofo)',
  'Pacific/Fiji': 'Fiji (Suva)',
  'Pacific/Funafuti': 'Tuvalu (Funafuti)',
  'Pacific/Galapagos': 'Ecuador (Galapagos)',
  'Pacific/Gambier': 'French Polynesia (Gambier)',
  'Pacific/Guadalcanal': 'Solomon Islands (Honiara)',
  'Pacific/Guam': 'Guam (Hagatna)',
  'Pacific/Honolulu': 'USA (Honolulu)',
  'Pacific/Kiritimati': 'Kiribati (Kiritimati)',
  'Pacific/Kosrae': 'Micronesia (Kosrae)',
  'Pacific/Kwajalein': 'Marshall Islands (Kwajalein)',
  'Pacific/Majuro': 'Marshall Islands (Majuro)',
  'Pacific/Marquesas': 'French Polynesia (Marquesas)',
  'Pacific/Midway': 'USA (Midway)',
  'Pacific/Nauru': 'Nauru (Yaren)',
  'Pacific/Niue': 'Niue (Alofi)',
  'Pacific/Norfolk': 'Norfolk Island (Kingston)',
  'Pacific/Noumea': 'New Caledonia (Noumea)',
  'Pacific/Pago_Pago': 'American Samoa (Pago Pago)',
  'Pacific/Palau': 'Palau (Ngerulmud)',
  'Pacific/Pitcairn': 'Pitcairn Islands (Adamstown)',
  'Pacific/Ponape': 'Micronesia (Pohnpei)',
  'Pacific/Port_Moresby': 'Papua New Guinea (Port Moresby)',
  'Pacific/Rarotonga': 'Cook Islands (Avarua)',
  'Pacific/Saipan': 'Northern Mariana Islands (Saipan)',
  'Pacific/Tahiti': 'French Polynesia (Tahiti)',
  'Pacific/Tarawa': 'Kiribati (Tarawa)',
  'Pacific/Tongatapu': 'Tonga (Nuku\'alofa)',
  'Pacific/Truk': 'Micronesia (Chuuk)',
  'Pacific/Wake': 'Wake Island (Wake Island)',
  'Pacific/Wallis': 'Wallis & Futuna (Mata-Utu)',

  // UTC / GMT
  'UTC': 'UTC',
  'GMT': 'GMT',
  'Etc/UTC': 'UTC',
  'Etc/GMT': 'GMT',
  'Etc/GMT+0': 'UTC',
  'Etc/GMT-0': 'UTC',
};

export const LEGACY_TIMEZONE_ALIASES = {
  'Asia/Calcutta': 'Asia/Kolkata',
  'Asia/Saigon': 'Asia/Ho_Chi_Minh',
  'Asia/Katmandu': 'Asia/Kathmandu',
  'Asia/Rangoon': 'Asia/Yangon',
  'Europe/Kiev': 'Europe/Kyiv',
};

/**
 * Normalize legacy IANA timezone identifiers to their modern canonical equivalents
 * @param {string} tz - IANA timezone identifier
 * @returns {string} Modern IANA timezone identifier
 */
export function normalizeTimezone(tz) {
  if (!tz) return 'UTC';
  return LEGACY_TIMEZONE_ALIASES[tz] || tz;
}

/**
 * Get friendly display name for a timezone
 * @param {string} ianaTimezone - IANA timezone identifier (e.g., "Asia/Kolkata")
 * @returns {string} Friendly name (e.g., "India (Kolkata)") or formatted fallback
 */
export function getFriendlyTimezoneName(ianaTimezone) {
  if (!ianaTimezone) return 'UTC';
  const normalized = normalizeTimezone(ianaTimezone);
  if (TIMEZONE_FRIENDLY_NAMES[normalized]) {
    return TIMEZONE_FRIENDLY_NAMES[normalized];
  }
  if (TIMEZONE_FRIENDLY_NAMES[ianaTimezone]) {
    return TIMEZONE_FRIENDLY_NAMES[ianaTimezone];
  }
  // Smart fallback: parse Region/Subregion/City and clean up underscores
  if (ianaTimezone.includes('/')) {
    const parts = ianaTimezone.split('/');
    const city = parts[parts.length - 1].replace(/_/g, ' ');
    const region = parts[0].replace(/_/g, ' ');
    return `${region} (${city})`;
  }
  return ianaTimezone;
}

/**
 * Get display label for dropdown: "Country (City) ±HH:MM"
 * @param {string} ianaTimezone - IANA timezone identifier
 * @param {string} offset - Formatted UTC offset (e.g., "+05:30")
 * @returns {string} Full display label
 */
export function getTimezoneDisplayLabel(ianaTimezone, offset) {
  const friendly = getFriendlyTimezoneName(ianaTimezone);
  return `${friendly} ${offset}`;
}